"""empty message

Revision ID: 174425740b10
Revises: 1fc6b4f52fee
Create Date: 2021-05-10 02:51:58.329955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174425740b10'
down_revision = '1fc6b4f52fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
