"""empty message

Revision ID: 9054abc25de8
Revises: ec9f9756de0f
Create Date: 2021-05-17 02:10:29.140695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9054abc25de8'
down_revision = 'ec9f9756de0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_tokens', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_column('blacklist_tokens', 'pk')
    op.add_column('users', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_column('users', 'pk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pk', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('users', 'id')
    op.add_column('blacklist_tokens', sa.Column('pk', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('blacklist_tokens', 'id')
    # ### end Alembic commands ###
